### ISSUE TITLE
Admin - Documents - Document Manager - Work Area - Folder Interactions

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#155]
- [x] Add a top-level, placeholding banner folder (e.g. Sport Chek) at the top of the tree (see #153)
  - [x] the banner folder should be expanded by default (its immediate child folders are visible)
- [x] if a given folder is expanded/collapsed, its folder icon should consistently reflect this
- [x] clicking on a folder icon should just expand/collapse the folder
- [x] clicking on a folder name should only list its contents on the right-hand side of the interface (see #156 )
- [x] folder names should be displayed exactly as entered/saved (no CSS capitalization)

**Comment by jyoti5337** [comment]
Not an issue - already working

- [ ] clicking on a folder name should list its contents on the right-hand side of the interface (see #156 )
- [ ] folder names should be displayed exactly as entered/saved (no CSS capitalization)

**Comment by darylsuttie** [comment]
To be clear, ensure that clicking the folder name *only* triggers the contents display and *does not* toggle folder expand/collapse.

At any rate, if it already works this way, just check the box, no comment necessary.

**Comment by darylsuttie** [comment]
Closing this issue.

As discussed, this doesn't actually pass, but in the interest of time, the folder interaction revision piece now has its own issue #223
