### ISSUE TITLE
Admin - Documents - Merge Manage Folders into Document Manager and rename

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#160]
**NOTE**
Resolving this issue will result in the merging of currently separate *Manage Folders* functionality into *Document Management*.

**Navigation**
- [x] Rename **Documents** tab within left navigation to **Library** and change its icon to fa-book
- [x] The **Library** tab will now point to what was previously called **Document Manager**

**Manage Folders**
- [x] Remove this area/tab/etc. completely

**Document Manager**
- [x] Rename **Library**
- [x] Remove the secondary link *Document Manager* from the left nav (since primary nav Library now points here)

*Folder Management (Folder tree)*
- [x] Add a placeholding, uneditable, top-level folder for the banner (e.g. Sport Chek).
  - [x] By default, this root/banner folder should always be expanded so all its first-level child folders are visible.
  - [x] on initial page load, this folder is "selected" (its name appears above the folder listing like any other folder's)
  - [x] When this folder is selected, only the **Add subfolder** button (see below) should be enabled. (i.e. it's not possible to add files to, delete, or rename this folder

*File Listing - added functionality*
Reference image
![admin-documents-manage-files-merge-folder-mgmt](https://cloud.githubusercontent.com/assets/830373/13608057/48e33102-e510-11e5-8c59-b70d0f4235a0.png)

- [x] Rename *Add files* button *Add documents*
* To the right of *Add documents*, add these buttons
  - [x] Add subfolder (fa-plus icon and fa-folder icon)
    - [ ] triggers Add subfolder modal - see #151 
  - [x] Rename folder (fa-pencil icon)
    - [ ] triggers Rename folder modal - see #152 
  - [x] Delete folder (fa-trash icon)
    - [ ] triggers folder delete confirmation modal - see #162

**Comment by darylsuttie** [comment]
@jyoti5337 Please review.

**Comment by darylsuttie** [comment]
Added the folder management piece I failed to pass through from the older issue I closed.

**Comment by bgarner** [comment]
fixed in e7cabfbf2d7acfdb838a2e0e2c53c247bd82bfee

**Comment by darylsuttie** [comment]
@bgarner @jyoti5337 

This issue is closed. Nice!
