### ISSUE TITLE
Admin - Events - Create Event - Defaults

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#304]
- [x] Event Type should default to undefined (display text: *Select Event Type*) but remain a required field
- [x] Stores selector should default to All Stores (Related: #303 )

**Comment by jyoti5337** [comment]
QA
#- [ ] Event Type should default to undefined (display text: *Select Event Type*) but remain a required field
- [ ] Stores selector should default to All Stores (Related: #303 )

**Comment by jyoti5337** [comment]
QA
- [ ] Event Type should default to undefined (display text: *Select Event Type*) but remain a required field
- [ ] Stores selector should default to All Stores (Related: #303 )
